=pod

=encoding UTF-8

=head1 NAME

AI::TensorFlow::Libtensorflow - Bindings for TensorFlow deep learning library

=head1 VERSION

version 0.001

=head1 AUTHOR

Zakariyya Mughal <zmughal@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is Copyright (c) 2021 by EntropyOrg.

This is free software, licensed under:

  The Apache License, Version 2.0, January 2004

=cut
