#!/bin/bash

set -exu

export MAKEFLAGS="-j$(nproc)"
export CPM_WORKERS=$(nproc)

cpanm --local-lib=~/perl5 -nq local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
cpanm -nq App::cpm

KERNEL="Devel::IPerl"
MODULES="AI::TensorFlow::Libtensorflow"
ALL_MODULES="$KERNEL $MODULES"

cpm install -g -w $CPM_WORKERS $ALL_MODULES  \
	|| cpanm -nq $ALL_MODULES

cpm install -g -w $CPM_WORKERS --cpanfile=<( \
	awk '/=head1 CPANFILE/,EOF {print}' < lib/AI/TensorFlow/Libtensorflow/Manual/InferenceUsingTFHubMobileNetV2Model.pod \
	| awk 'NR>1' \
	)

iperl --version # install kernel and exit
