#syntax=docker/dockerfile-upstream:1.4.0-rc1

# OMNIBUS

# Builds on top of:
#   - docker/Dockerfile.nb-image-class
#   - docker/Dockerfile.nb-bioinfo
#
# The contents of `NB_APT_PKGS_RUN` come from those `Dockerfile`s.
ARG NB_APT_PKGS_RUN=" \
libjpeg-turbo8     libpng16-16 libgsl23 \
samtools libhts3 tabix libxml2 libexpat1 libdb5.3 netpbm gnuplot-nox \
"

FROM base as omnibus

ARG NB_APT_PKGS_RUN

COPY --from=nb-image-class /perl5-nb /perl5-nb-image-class
COPY --from=nb-bioinfo     /perl5-nb /perl5-nb-bioinfo

RUN apt-get update && apt-get install -y --no-install-recommends $NB_APT_PKGS_RUN

RUN \
	   mkdir -p                                           /perl5-nb \
	&& cp -pR /perl5-nb-image-class/. /perl5-nb-bioinfo/. /perl5-nb/ \
	&& rm -Rf /perl5-nb-image-class   /perl5-nb-bioinfo

RUN apt-get autoremove -y && apt-get clean
RUN rm -Rf $HOME/.perl-cpm/ $HOME/.cpanm

# vim:ft=dockerfile
